<a href="https://colab.research.google.com/github/linguist7/SkillTreePython-DataAnalysis/blob/main/01.%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EA%B8%B0%EC%B4%88/08_Pandas_%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ch.08 Pandas - 데이터 다루기
---
* 날짜:
* 이름:

## 개념정리
---

```
import pandas as pd
import numpy as np
```

In [44]:
import pandas as pd
import numpy as np

실습을 위해 캘리포니아 데이터셋을 불러옵니다.
```
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
df.head()
```

In [45]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

---
### **(1) 데이터 수정**
---

인덱싱과 슬라이싱을 이용해 원하는 값에 접근하고 변경할 수 있습니다.


#### **| 인덱싱, 슬라이싱 사용**

( `0` 행, `logitude` 열) 의 값을 100으로 바꿔 봅시다.

```
df.loc[0, 'longitude'] = 100
df.head()
```

In [46]:
df.loc[0, 'longitude'] = 100
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,100.00,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

( `0` 행~`2` 행, `logitude` ~ `latitude` 열) 의 값을 100으로 바꿔 봅시다.

```
df.loc[:2, 'longitude':'latitude'] = 100
df.head()
```

In [47]:
df.loc[:2, 'longitude':'latitude'] = 100
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,100.00,100.00,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,100.00,100.00,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,100.00,100.00,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

#### **| 컬럼명 변경**

* `df.columns` : 열 네이밍을 바인딩으로 새로 지정할 수 있습니다.

```
df.columns = [ f'A{i}' for i in range(9)]
df.head()
```

In [48]:
df.columns = [ f'A{i}' for i in range(9)]
df.head()

       A0      A1    A2      A3     A4      A5     A6      A7        A8
0  100.00  100.00  27.0  3885.0  661.0  1537.0  606.0  6.6085  344700.0
1  100.00  100.00  43.0  1510.0  310.0   809.0  277.0  3.5990  176500.0
2  100.00  100.00  27.0  3589.0  507.0  1484.0  495.0  5.7934  270500.0
3 -118.36   33.82  28.0    67.0   15.0    49.0   11.0  6.1359  330000.0
4 -119.67   36.33  19.0  1241.0  244.0   850.0  237.0  2.9375   81700.0

* `.rename({before:after}, axis, inplace)`

바꿀 목표와 바꿀 이름을 적어주고, 행인지 열인지 `axis`로 정해줍니다.

```
df.rename({"A0":"B0", "A2":"B2"}, axis = 1)
df.head()
```

In [49]:
df = df.rename({3:"33", 4:"44"}, axis= 0 )          
df.head()

        A0      A1    A2      A3     A4      A5     A6      A7        A8
0   100.00  100.00  27.0  3885.0  661.0  1537.0  606.0  6.6085  344700.0
1   100.00  100.00  43.0  1510.0  310.0   809.0  277.0  3.5990  176500.0
2   100.00  100.00  27.0  3589.0  507.0  1484.0  495.0  5.7934  270500.0
33 -118.36   33.82  28.0    67.0   15.0    49.0   11.0  6.1359  330000.0
44 -119.67   36.33  19.0  1241.0  244.0   850.0  237.0  2.9375   81700.0

#### **| 범주 나누기**

* `pd.cut(열, bins, labels)` : `bins` 범위의 숫자를 `names`로 범주를 나눕니다.

`A2`의 깂들을 범주화 하겠습니다.

```
bins = [0,10,20,30,40,100]
names = ['a','b','c','d','e']
df['A2']=pd.cut(df['A2'], bins=bins, labels=names)
df.head()
```

In [50]:
df['B2'].describe()
bins = [0, 18, 29, 37, 60] # 4분위로 나눔
names = ['a', 'b', 'c', 'd']
df['B2'] = pd.cut(df['B2'], bins=bins, labels=names)
df.head()

KeyError: ignored

**'변수.groupby(column)'**

In [51]:
df.groupby('B2')['A4'].sum()   #  A4열을  B2를 기준으로 . 합계

KeyError: ignored

---
### **(2) 데이터 추가**
---

#### **| 행 추가**

새로운 행을 작성합니다.

```
line = np.zeros(9)
line
```

In [52]:
line = np.zeros(9)
line

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

인덱싱을 이용해 새로운 행을 추가할 수 있습니다.


```
df.loc[3001] = line
df.tail()
```

In [53]:
df.loc[3001] = line
df.tail()

          A0     A1    A2      A3      A4      A5      A6      A7        A8
2996 -118.14  34.06  27.0  5257.0  1082.0  3496.0  1036.0  3.3906  237200.0
2997 -119.70  36.30  10.0   956.0   201.0   693.0   220.0  2.2895   62000.0
2998 -117.12  34.10  40.0    96.0    14.0    46.0    14.0  3.2708  162500.0
2999 -119.63  34.42  42.0  1765.0   263.0   753.0   260.0  8.5608  500001.0
3001    0.00   0.00   0.0     0.0     0.0     0.0     0.0  0.0000       0.0

#### **| 열 추가**

새로운 열 `safety`를 만들어 보겠습니다. 총 5개의 등급으로 이루어져 있습니다.

```
col_list = ['A-a', 'A-b', 'B-a', 'B-b', 'C']
col = np.random.choice(col_list, len(df))
col, col.shape
```

In [54]:
col_list = ['A-a', 'A-b', 'B-a', 'B-b', 'C'] #안전등급
col = np.random.choice(col_list, len(df)) #데이터 개수(3001)만큼 안전등급 랜덤 뽑기함
col, col.shape

(array(['B-b', 'B-b', 'C', ..., 'B-a', 'B-b', 'A-b'], dtype='<U3'), (3001,))

인덱싱을 이용하여 `safety`를 추가합니다.

```
df['safety']=safety
df.head()
```

In [55]:
df['safety']= col
df.head()

,A0,A1,A2,A3,A4,A5,A6,A7,A8,safety
0,100.00,100.00,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,B-b
1,100.00,100.00,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,B-b
2,100.00,100.00,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,C
33,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,A-a
44,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,B-b

---
### **(2) 데이터 삭제**
---

#### **| 기본사용**

* `.drop( idx, axis)` : `axis` 방향의 `idx` 데이터 제거

```
df = df.drop(0)
df.head()
```

In [56]:
df = df.drop(0)
df.head()

,A0,A1,A2,A3,A4,A5,A6,A7,A8,safety
1,100.00,100.00,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,B-b
2,100.00,100.00,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,C
33,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,A-a
44,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,B-b
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0,A-b

여러개의 행을 지워 봅시다.

```
df = df.drop([1,2])
df.head()
```

In [57]:
df = df.drop([1,2]) #명시적
df.head()

        A0     A1    A2      A3     A4      A5     A6      A7        A8 safety
33 -118.36  33.82  28.0    67.0   15.0    49.0   11.0  6.1359  330000.0    A-a
44 -119.67  36.33  19.0  1241.0  244.0   850.0  237.0  2.9375   81700.0    B-b
5  -119.56  36.51  37.0  1018.0  213.0   663.0  204.0  1.6635   67000.0    A-b
6  -121.43  38.63  43.0  1009.0  225.0   604.0  218.0  1.6641   67000.0    A-b
7  -120.65  35.48  19.0  2310.0  471.0  1341.0  441.0  3.2250  166900.0    A-b

열을 지울 때는 `axis=1`를 추가합니다.

```
df = df.drop(['A7','A8'], axis=1)
df.head()
```

In [58]:
df = df.drop(['A7','A8'], axis=1)
df.head()

        A0     A1    A2      A3     A4      A5     A6 safety
33 -118.36  33.82  28.0    67.0   15.0    49.0   11.0    A-a
44 -119.67  36.33  19.0  1241.0  244.0   850.0  237.0    B-b
5  -119.56  36.51  37.0  1018.0  213.0   663.0  204.0    A-b
6  -121.43  38.63  43.0  1009.0  225.0   604.0  218.0    A-b
7  -120.65  35.48  19.0  2310.0  471.0  1341.0  441.0    A-b

#### **| 결측치 삭제**

데이터에는 결측치가 포함된 경우가 종종 있습니다. 결측치를 삭제하는 방법을 알아봅니다.

이를 위해 데이터에 `nan`값을 추가합니다.

```
df.loc[[3,5],'A0']=float('nan')
df.head()
```

In [61]:
df.loc[[5,6],'A0']=float('nan')
df.head()

        A0     A1    A2      A3     A4      A5     A6 safety
33 -118.36  33.82  28.0    67.0   15.0    49.0   11.0    A-a
44 -119.67  36.33  19.0  1241.0  244.0   850.0  237.0    B-b
5      NaN  36.51  37.0  1018.0  213.0   663.0  204.0    A-b
6      NaN  38.63  43.0  1009.0  225.0   604.0  218.0    A-b
7  -120.65  35.48  19.0  2310.0  471.0  1341.0  441.0    A-b

* `.dropna(axis)` : 결측값이 포함된 `axis`를 삭제합니다. ( 기본 `axis=0` )

In [63]:
df.dropna()

          A0     A1    A2      A3      A4      A5      A6 safety
33   -118.36  33.82  28.0    67.0    15.0    49.0    11.0    A-a
44   -119.67  36.33  19.0  1241.0   244.0   850.0   237.0    B-b
7    -120.65  35.48  19.0  2310.0   471.0  1341.0   441.0    A-b
8    -122.84  38.40  15.0  3080.0   617.0  1446.0   599.0      C
9    -118.02  34.08  31.0  2402.0   632.0  2830.0   603.0    A-a
...      ...    ...   ...     ...     ...     ...     ...    ...
2996 -118.14  34.06  27.0  5257.0  1082.0  3496.0  1036.0    B-a
2997 -119.70  36.30  10.0   956.0   201.0   693.0   220.0    A-b
2998 -117.12  34.10  40.0    96.0    14.0    46.0    14.0    B-a
2999 -119.63  34.42  42.0  1765.0   263.0   753.0   260.0    B-b
3001    0.00   0.00   0.0     0.0     0.0     0.0     0.0    A-b

[2996 rows x 8 columns]

---
### **(3) 마스킹**
---

마스킹이란 넘파이의 불리언 인덱싱과 같은 개념으로 보시면 됩니다. 원하는 조건에 맞는 데이터만 출력할 수 있습니다.

#### **| 인덱싱을 이용한 마스킹**


열 `safety`에서 값이 `A-b`인 마스크를 바인딩 합니다.

```
mask = df['safety'] == 'A-b'
mask
```

In [64]:
mask = df['safety'] == 'A-b'
mask

33      False
44      False
5        True
6        True
7        True
        ...
2996    False
2997     True
2998    False
2999    False
3001     True
Name: safety, Length: 2998, dtype: bool

마스크를 이용해 해당하는 데이터만 출력합니다.
```
df_masked = df[mask]
df_masked.head()
```

In [65]:
df_masked = df[mask]
df_masked.head()

        A0     A1    A2      A3     A4      A5     A6 safety
5      NaN  36.51  37.0  1018.0  213.0   663.0  204.0    A-b
6      NaN  38.63  43.0  1009.0  225.0   604.0  218.0    A-b
7  -120.65  35.48  19.0  2310.0  471.0  1341.0  441.0    A-b
15 -117.99  33.81  42.0   161.0   40.0   157.0   50.0    A-b
16 -120.81  37.53  15.0   570.0  123.0   189.0  107.0    A-b

두가지 조건을 다음과 같이 줄 수 있습니다.

```
mask = (df['safety']=='A-b') | (df['safety']=='A-a')
df_masked = df[mask]
df_masked.head()

```

In [66]:
mask = (df['safety']=='A-b') | (df['safety']=='A-a')
df_masked = df[mask]
df_masked.head()

        A0     A1    A2      A3     A4      A5     A6 safety
33 -118.36  33.82  28.0    67.0   15.0    49.0   11.0    A-a
5      NaN  36.51  37.0  1018.0  213.0   663.0  204.0    A-b
6      NaN  38.63  43.0  1009.0  225.0   604.0  218.0    A-b
7  -120.65  35.48  19.0  2310.0  471.0  1341.0  441.0    A-b
9  -118.02  34.08  31.0  2402.0  632.0  2830.0  603.0    A-a

#### **| `isin`을 이용한 마스킹**

* `.isin([val_list])`

열 `safety`에서 값이 `A-b`인 마스크를 바인딩 합니다.

```
mask = df['safety'].isin(['A-b'])
mask
```

In [67]:
mask = df['safety'].isin(['A-b'])
mask

33      False
44      False
5        True
6        True
7        True
        ...
2996    False
2997     True
2998    False
2999    False
3001     True
Name: safety, Length: 2998, dtype: bool

마스크를 이용해 해당하는 데이터만 출력합니다.
```
df_masked = df[mask]
df_masked.head()
```

In [68]:
df_masked = df[mask]
df_masked.head()

        A0     A1    A2      A3     A4      A5     A6 safety
5      NaN  36.51  37.0  1018.0  213.0   663.0  204.0    A-b
6      NaN  38.63  43.0  1009.0  225.0   604.0  218.0    A-b
7  -120.65  35.48  19.0  2310.0  471.0  1341.0  441.0    A-b
15 -117.99  33.81  42.0   161.0   40.0   157.0   50.0    A-b
16 -120.81  37.53  15.0   570.0  123.0   189.0  107.0    A-b

`isin`을 사용하면 여러개의 값을 한번에 찾을 때 유용합니다.
```
mask = df['safety'].isin(['A-b', 'A-a'])
df_masked = df[mask]
df_masked.head()
```

In [69]:
mask = df['safety'].isin(['A-b', 'A-a'])
df_masked = df[mask]
df_masked.head()

        A0     A1    A2      A3     A4      A5     A6 safety
33 -118.36  33.82  28.0    67.0   15.0    49.0   11.0    A-a
5      NaN  36.51  37.0  1018.0  213.0   663.0  204.0    A-b
6      NaN  38.63  43.0  1009.0  225.0   604.0  218.0    A-b
7  -120.65  35.48  19.0  2310.0  471.0  1341.0  441.0    A-b
9  -118.02  34.08  31.0  2402.0  632.0  2830.0  603.0    A-a

#### **| 마스킹을 이용한 데이터 수정**

우선 `A-a`에 해당하는 마스크를 만듭시다.

```
mask = df['safety']=='A-a'
mask
```

In [73]:
mask = df['safety']=='A-a'
mask

33      False
44      False
5       False
6       False
7       False
        ...
2996    False
2997    False
2998    False
2999    False
3001    False
Name: safety, Length: 2998, dtype: bool

기본적으로 마스크로 인덱싱한 값을 바꾸면 마스크에 속하는 행의 모든 값이 바뀝니다.

```
df[mask]='값수정1'
df
```

In [71]:
df[mask]='값수정1'
df

          A0     A1    A2      A3      A4      A5      A6 safety
33      값수정1   값수정1  값수정1    값수정1    값수정1    값수정1    값수정1   값수정1
44   -119.67  36.33  19.0  1241.0   244.0   850.0   237.0    B-b
5        NaN  36.51  37.0  1018.0   213.0   663.0   204.0    A-b
6        NaN  38.63  43.0  1009.0   225.0   604.0   218.0    A-b
7    -120.65  35.48  19.0  2310.0   471.0  1341.0   441.0    A-b
...      ...    ...   ...     ...     ...     ...     ...    ...
2996 -118.14  34.06  27.0  5257.0  1082.0  3496.0  1036.0    B-a
2997  -119.7   36.3  10.0   956.0   201.0   693.0   220.0    A-b
2998 -117.12   34.1  40.0    96.0    14.0    46.0    14.0    B-a
2999 -119.63  34.42  42.0  1765.0   263.0   753.0   260.0    B-b
3001     0.0    0.0   0.0     0.0     0.0     0.0     0.0    A-b

[2998 rows x 8 columns]

마스크에 속하는 행의 특정 열만 바꾸고 싶다면 `loc` 또는 `iloc`을 써서 열을 제한해 줍니다. 

```
df.loc[mask, 'safety']='값수정2'
df
```

In [74]:
df.loc[mask, 'safety']='값수정2'
df

          A0     A1    A2      A3      A4      A5      A6 safety
33      값수정1   값수정1  값수정1    값수정1    값수정1    값수정1    값수정1   값수정2
44   -119.67  36.33  19.0  1241.0   244.0   850.0   237.0    B-b
5        NaN  36.51  37.0  1018.0   213.0   663.0   204.0    A-b
6        NaN  38.63  43.0  1009.0   225.0   604.0   218.0    A-b
7    -120.65  35.48  19.0  2310.0   471.0  1341.0   441.0    A-b
...      ...    ...   ...     ...     ...     ...     ...    ...
2996 -118.14  34.06  27.0  5257.0  1082.0  3496.0  1036.0    B-a
2997  -119.7   36.3  10.0   956.0   201.0   693.0   220.0    A-b
2998 -117.12   34.1  40.0    96.0    14.0    46.0    14.0    B-a
2999 -119.63  34.42  42.0  1765.0   263.0   753.0   260.0    B-b
3001     0.0    0.0   0.0     0.0     0.0     0.0     0.0    A-b

[2998 rows x 8 columns]

---
### **(4) 문자열**
---

데이터의 문자를 인식해서 각종 처리를 할 수 있습니다. 이 때 전체 데이터 프레임이 아닌 열에 대해서만 함수를 사용할 수 있습니다.

```
df['열'].str.함수()
```

`.str`을 이용해 간단한 인덱싱이 가능합니다. `safety`에서 첫번째 문자만 출력해 보겠습니다.

```
df['safety'].str[0]
```

In [76]:
df['safety'].str[-1]

33      2
44      b
5       b
6       b
7       b
       ..
2996    a
2997    b
2998    a
2999    b
3001    b
Name: safety, Length: 2998, dtype: object

#### **| 글자인식**

글자인식을 통해 해당하는 문자이면 `True , False`로 반환합니다. 따라서 이를 이용해 마스킹을 사용할 수 있습니다.



* `.str.contains(s)` : 문자열 `s`가 포함된 모든 행을 검색합니다.

문자열이 값 안에 포함되어 있는지 검색할 때 유용합니다. 안전등급에 `A`가 포함된 값을 모두 찾아 보겠습니다.

```
 mask = df['safety'].str.contains('A')
 mask
 ```

In [77]:
 mask = df['safety'].str.contains('B')
 mask

33      False
44       True
5       False
6       False
7       False
        ...
2996     True
2997    False
2998     True
2999     True
3001    False
Name: safety, Length: 2998, dtype: bool

위에서 만든 마스크를 씌우고 결과를 확인합니다.

```
df_maksed=df[mask]
df_masked.head()
```

In [80]:
df_maksed=df[mask]
df_masked

          A0     A1    A2      A3     A4      A5     A6 safety
33   -118.36  33.82  28.0    67.0   15.0    49.0   11.0    A-a
5        NaN  36.51  37.0  1018.0  213.0   663.0  204.0    A-b
6        NaN  38.63  43.0  1009.0  225.0   604.0  218.0    A-b
7    -120.65  35.48  19.0  2310.0  471.0  1341.0  441.0    A-b
9    -118.02  34.08  31.0  2402.0  632.0  2830.0  603.0    A-a
...      ...    ...   ...     ...    ...     ...    ...    ...
2992 -122.33  37.39  52.0   573.0  102.0   232.0   92.0    A-b
2993 -117.91  33.60  37.0  2088.0  510.0   673.0  390.0    A-a
2995 -119.86  34.42  23.0  1450.0  642.0  1258.0  607.0    A-a
2997 -119.70  36.30  10.0   956.0  201.0   693.0  220.0    A-b
3001    0.00   0.00   0.0     0.0    0.0     0.0    0.0    A-b

[1219 rows x 8 columns]

문자열이 특정 문자로 시작되거나 끝나는지의 여부도 아래의 함수를 이용해 확인할 수 있습니다.


* `.str.stratswith(s)` : 문자열 `s`로 시작되는지 여부를 반환합니다 (`True/False`)

* `.str.endswith(s)` : 문자열 `s`로 끝나는지 여부를 반환합니다 (`True/False`)

```
mask = df['safety'].str.endswith('b')
df_masked = df[mask]
df_masked.head()
```

In [81]:
mask = df['safety'].str.endswith('b')
df_masked = df[mask]
df_masked.head()

        A0     A1    A2      A3     A4      A5     A6 safety
44 -119.67  36.33  19.0  1241.0  244.0   850.0  237.0    B-b
5      NaN  36.51  37.0  1018.0  213.0   663.0  204.0    A-b
6      NaN  38.63  43.0  1009.0  225.0   604.0  218.0    A-b
7  -120.65  35.48  19.0  2310.0  471.0  1341.0  441.0    A-b
10 -118.24  33.98  45.0   972.0  249.0  1288.0  261.0    B-b

In [87]:
df.loc[:10] #행분할

        A0     A1    A2      A3     A4      A5     A6 safety
33    값수정1   값수정1  값수정1    값수정1   값수정1    값수정1   값수정1   값수정2
44 -119.67  36.33  19.0  1241.0  244.0   850.0  237.0    B-b
5      NaN  36.51  37.0  1018.0  213.0   663.0  204.0    A-b
6      NaN  38.63  43.0  1009.0  225.0   604.0  218.0    A-b
7  -120.65  35.48  19.0  2310.0  471.0  1341.0  441.0    A-b
8  -122.84   38.4  15.0  3080.0  617.0  1446.0  599.0      C
9     값수정1   값수정1  값수정1    값수정1   값수정1    값수정1   값수정1   값수정2
10 -118.24  33.98  45.0   972.0  249.0  1288.0  261.0    B-b

#### **| 열 분할**

* `.str.split(s)` : 특정 열을 문자열 기준으로 나눕니다

```
df['safety'].str.split('-', expand = True).head() 
```

In [ ]:
df['safety'].str.split('-', expand = True)

#### **| 문자 교체**

* `.str.replace(s1,s2 )` : 문자열 `s1`을 `s2`로 바꿉니다.

```
df['safety'].str.replace('-', ':').head()
```

In [92]:
df['safety'].str.replace('-', ':').head()

33    값수정2
44     B:b
5      A:b
6      A:b
7      A:b
Name: safety, dtype: object

## 문제풀이
---

**예제 01**

다음과 같이 연도, 월, 날짜가 기입된 데이터프레임을 작성하고 `df01` 로 바인딩하세요.

2001년 1-1일 부터 2001년 2-28일까지 기입되어 있습니다. (31+28= 총 59줄)


| index | 연도 | 날짜 | 
|--|--|--|
|0|2001|1-1|
|1|2001|1-2|
|2|2001|1-3|
||...|

In [248]:
a = np.arange(59)
a1 = a.reshape((59,1))
df = pd.DataFrame(a1)

df['연도'] = 2001
month_1 = [f'1-{i}' for i in range(1, 32)]
month_2 = [f'2-{i}' for i in range(1, 29)]
df['날짜'] = month_1 + month_2
df01 = df.drop(0, axis=1)

df01

      연도    날짜
0   2001   1-1
1   2001   1-2
2   2001   1-3
3   2001   1-4
4   2001   1-5
5   2001   1-6
6   2001   1-7
7   2001   1-8
8   2001   1-9
9   2001  1-10
10  2001  1-11
11  2001  1-12
12  2001  1-13
13  2001  1-14
14  2001  1-15
15  2001  1-16
16  2001  1-17
17  2001  1-18
18  2001  1-19
19  2001  1-20
20  2001  1-21
21  2001  1-22
22  2001  1-23
23  2001  1-24
24  2001  1-25
25  2001  1-26
26  2001  1-27
27  2001  1-28
28  2001  1-29
29  2001  1-30
30  2001  1-31
31  2001   2-1
32  2001   2-2
33  2001   2-3
34  2001   2-4
35  2001   2-5
36  2001   2-6
37  2001   2-7
38  2001   2-8
39  2001   2-9
40  2001  2-10
41  2001  2-11
42  2001  2-12
43  2001  2-13
44  2001  2-14
45  2001  2-15
46  2001  2-16
47  2001  2-17
48  2001  2-18
49  2001  2-19
50  2001  2-20
51  2001  2-21
52  2001  2-22
53  2001  2-23
54  2001  2-24
55  2001  2-25
56  2001  2-26
57  2001  2-27
58  2001  2-28

**예제 02**

`df01`의 연도를 모두 2022로 바꾸세요.

In [249]:
df01['연도'] = 2002
df01

      연도    날짜
0   2002   1-1
1   2002   1-2
2   2002   1-3
3   2002   1-4
4   2002   1-5
5   2002   1-6
6   2002   1-7
7   2002   1-8
8   2002   1-9
9   2002  1-10
10  2002  1-11
11  2002  1-12
12  2002  1-13
13  2002  1-14
14  2002  1-15
15  2002  1-16
16  2002  1-17
17  2002  1-18
18  2002  1-19
19  2002  1-20
20  2002  1-21
21  2002  1-22
22  2002  1-23
23  2002  1-24
24  2002  1-25
25  2002  1-26
26  2002  1-27
27  2002  1-28
28  2002  1-29
29  2002  1-30
30  2002  1-31
31  2002   2-1
32  2002   2-2
33  2002   2-3
34  2002   2-4
35  2002   2-5
36  2002   2-6
37  2002   2-7
38  2002   2-8
39  2002   2-9
40  2002  2-10
41  2002  2-11
42  2002  2-12
43  2002  2-13
44  2002  2-14
45  2002  2-15
46  2002  2-16
47  2002  2-17
48  2002  2-18
49  2002  2-19
50  2002  2-20
51  2002  2-21
52  2002  2-22
53  2002  2-23
54  2002  2-24
55  2002  2-25
56  2002  2-26
57  2002  2-27
58  2002  2-28

**예제 03**

`df01` 에 1월, 2월에 이어서 3월을 추가하세요.

In [250]:
b = np.arange(30)
b1 = b.reshape((30,1))
df1 = pd.DataFrame(b1)

df1['연도'] = 2002
month_3 = [f'3-{i}' for i in range(1, 31)]
df1['날짜'] = month_3
df02 = df1.drop(0, axis=1)

df01 = pd.concat([df01,df02], axis=0, ignore_index=True)
df01

      연도    날짜
0   2002   1-1
1   2002   1-2
2   2002   1-3
3   2002   1-4
4   2002   1-5
..   ...   ...
84  2002  3-26
85  2002  3-27
86  2002  3-28
87  2002  3-29
88  2002  3-30

[89 rows x 2 columns]

**예제 05**

`df01`의 `날짜` 열에서 하이픈`-` 을 콤마`,`로 바꿔주세요.

In [251]:
df01['날짜'].str.replace("-",",").head()

0    1,1
1    1,2
2    1,3
3    1,4
4    1,5
Name: 날짜, dtype: object

**예제 06**

`df01`에 `요일` 열을 추가하세요. 첫번째 행의 시작은 `토요일` 입니다.

In [252]:
week = ['토요일','일요일','월요일','화요일','수요일','목요일','금요일']*15
df01['요일'] = week[:89]
df01

      연도    날짜   요일
0   2002   1-1  토요일
1   2002   1-2  일요일
2   2002   1-3  월요일
3   2002   1-4  화요일
4   2002   1-5  수요일
..   ...   ...  ...
84  2002  3-26  토요일
85  2002  3-27  일요일
86  2002  3-28  월요일
87  2002  3-29  화요일
88  2002  3-30  수요일

[89 rows x 3 columns]

**예제 07**

`목요일`에 해당하는 행을 모두 출력하세요.

In [253]:
mask = df01['요일'] =='목요일'
df01[mask]

      연도    날짜   요일
5   2002   1-6  목요일
12  2002  1-13  목요일
19  2002  1-20  목요일
26  2002  1-27  목요일
33  2002   2-3  목요일
40  2002  2-10  목요일
47  2002  2-17  목요일
54  2002  2-24  목요일
61  2002   3-3  목요일
68  2002  3-10  목요일
75  2002  3-17  목요일
82  2002  3-24  목요일

**예제 08**

`2`월에 해당하는 행 중 `날짜` 열과 `요일` 열만 출력하세요.

In [254]:
mask = df01['날짜'].str.startswith('2-')
df01[mask]

      연도    날짜   요일
31  2002   2-1  화요일
32  2002   2-2  수요일
33  2002   2-3  목요일
34  2002   2-4  금요일
35  2002   2-5  토요일
36  2002   2-6  일요일
37  2002   2-7  월요일
38  2002   2-8  화요일
39  2002   2-9  수요일
40  2002  2-10  목요일
41  2002  2-11  금요일
42  2002  2-12  토요일
43  2002  2-13  일요일
44  2002  2-14  월요일
45  2002  2-15  화요일
46  2002  2-16  수요일
47  2002  2-17  목요일
48  2002  2-18  금요일
49  2002  2-19  토요일
50  2002  2-20  일요일
51  2002  2-21  월요일
52  2002  2-22  화요일
53  2002  2-23  수요일
54  2002  2-24  목요일
55  2002  2-25  금요일
56  2002  2-26  토요일
57  2002  2-27  일요일
58  2002  2-28  월요일

**예제 09**

`날짜`의 데이터를 나눠 `월`과 `일`이라는 새로운 열을 `df01`에 추가하세요.

In [255]:
df02 = df01['날짜'].str.split('-', expand = True)
df01 = pd.concat([df01,df02], axis=1)
df01 = df01.rename({0:"월", 1:"일"}, axis = 1)
df01

      연도    날짜   요일  월   일
0   2002   1-1  토요일  1   1
1   2002   1-2  일요일  1   2
2   2002   1-3  월요일  1   3
3   2002   1-4  화요일  1   4
4   2002   1-5  수요일  1   5
..   ...   ...  ... ..  ..
84  2002  3-26  토요일  3  26
85  2002  3-27  일요일  3  27
86  2002  3-28  월요일  3  28
87  2002  3-29  화요일  3  29
88  2002  3-30  수요일  3  30

[89 rows x 5 columns]

**예제 10**

`df01`에서 `날짜` 열을 제거하세요.

In [257]:
df01 = df01.drop('날짜', axis=1)
df01

      연도   요일  월   일
0   2002  토요일  1   1
1   2002  일요일  1   2
2   2002  월요일  1   3
3   2002  화요일  1   4
4   2002  수요일  1   5
..   ...  ... ..  ..
84  2002  토요일  3  26
85  2002  일요일  3  27
86  2002  월요일  3  28
87  2002  화요일  3  29
88  2002  수요일  3  30

[89 rows x 4 columns]

---
최종 `df01`을 `ch08_days.csv`로 저장하고 깃허브에 올려주세요.

In [263]:
df01.to_csv('ch08_days.csv')